---
- hosts: dev
  user: vagrant

  roles:
    - { role: ssh , sudo: True}
    - { role: common }
    - { role: ruby, sudo: True }
    - { role: nodejs }
    - { role: mongodb }
    - { role: meanjs }